#include <Arduino.h>
#include <RadioLib.h>

//Heltec WiFi LoRa 32 V3 (SX1262) pin mapping
static constexpr int LORA_CS   = 8;   //Chip select/NSS (Prevents devices from talking over one anoter) [ESP32->SX1262]
static constexpr int LORA_SCK  = 9;   //Serial clock (generated by ESP32) [Syncs SPI]
static constexpr int LORA_MOSI = 10;  //Master out, Slave in (Sending data) [ESP32->SX1262]
static constexpr int LORA_MISO = 11;  //Master out, Slave in (Sending data) [SX1262->ESP32]
static constexpr int LORA_RST  = 12;  //Reset [ESP32->SX1262]
static constexpr int LORA_BUSY = 13;  //Busy (Only send SPI cmds when BUSY is low) [SX1262->ESP32]
static constexpr int LORA_DIO1 = 14;  //Interrupt/Event (Low power/Notifies ESP32 when event occurs) [SX1262->ESP32]

static constexpr int ADC_CTRL  = 37;  //[ADC_CTRL(37) *pin needs to be pulled high to read the lithium battery voltage*]
static constexpr int VBAT_PIN  = 1;   

SX1262 radio = new Module(LORA_CS, LORA_DIO1, LORA_RST, LORA_BUSY);

void setup() {
  
  Serial.begin(115200);
  delay(1500);
  /*Boot benchmark***********************************************************************************************************************/
  Serial.println("Boot OK");

  /*Battery reading benchmark*************************************************************************************************************/
  pinMode(ADC_CTRL, OUTPUT);        // Set as output pin
  digitalWrite(ADC_CTRL, HIGH);     // Set as high [ADC_CTRL(37) pin needs to be pulled high to read the lithium battery voltage]
  
  analogReadResolution(12);         // 12 bit ADC (0-4095). ~1.65V = ~2048 // ~3.3V = ~4095
  analogSetAttenuation(ADC_11db);   // Allows ~3.3V range

  /*Transmit LoRa pkt benchmark***********************************************************************************************************/
  Serial.println("Initializing LoRa...");
  int state = radio.begin(915.0); // 915 = US Region

  //Init error detection
  if (state != RADIOLIB_ERR_NONE) {
    Serial.printf("LoRa init failed: %d\n", state);
    while (true);
  }
  //Init success msg
  Serial.println("LoRa OK");
}

void sendPacket(){
  radio.transmit("hello");
  delay(5000);
}

float readBatteryVoltage(){
  int raw = analogRead(VBAT_PIN);
  //Convert raw ADC into voltage at ADC pin
  float V_ADC = (raw / 4095.0) * 3.3;
  //Convert to actual battery voltage [(100+390)/100]
  float V_BAT = V_ADC * 4.9;
  return V_BAT;
}

void loop(){
  Serial.println("Alive"); //Boot
  delay(1000);

  Serial.println("VBAT test starting"); //Batt
  float V_BAT = readBatteryVoltage();
  Serial.printf("Battery volate: %.2f V\n", V_BAT);
  delay(1000);

  Serial.println("Sending packet..."); //TX
  sendPacket();

  Serial.println("Going to sleep..."); //Sleep/wake (send back to setup)
  esp_sleep_enable_timer_wakeup(10 * 1000000ULL); // 10 seconds
  esp_deep_sleep_start();
}